### ISSUE TITLE
Exposing `dlpack` interface for Julia `Array`/`CuArray`

### ISSUE THREAD

**Issue by rejuvyesh** [pabloferz/DLPack.jl#10]
I think the current code only handles the `from_dlpack` via `unsafe_wrap` but not the `to_dlpack` part.

**Comment by pabloferz** [comment]
I'm just hesitant about the memory management default behaviour. But I'm inclined toward converting and making a responsibility of python to garbage collect.

**Comment by rejuvyesh** [comment]
There is also the issue of `row-major` vs `col-major`. In https://github.com/rejuvyesh/PyCallChainRules.jl/pull/10 I am doing:

```julia
rowmajor2colmajor(a::AbstractArray{T,2}) where {T<:AbstractFloat} = a
rowmajor2colmajor(a::AbstractArray{T,1}) where {T<:AbstractFloat} = a

function rowmajor2colmajor(a::AbstractArray{T,N}) where {T<:AbstractFloat,N}
    PermutedDimsArray(reshape(a, reverse(size(a))...), N:-1:1)
end

function via_dlpack(x)
    return rowmajor2colmajor(Base.unsafe_wrap(Array, DLArray{Float32,x.dim()}(@pycall dlpack.to_dlpack(x)::PyObject)))
end
```

In case you know of a better way, would love to know!

**Comment by pabloferz** [comment]
`PermuteDimsArray` is, I'd say the canonical way to do this. I didn't want to make that part of the interface and allow the user to decide, but I could of course provide an easy way to have this out of the box along the lines of what you have here.

**Comment by rejuvyesh** [comment]
Maybe useful to at least document it somewhere even if you don't want this to be explicitly part of the API.

**Comment by pabloferz** [comment]
One thing I still have not clear is what the behavior of something like `to_dlpack` would be in terms of the memory layout. Should python users be warned that the memory is col major and that's it?

**Comment by rejuvyesh** [comment]
I am not sure if there are any other col major layout consumers of `dlpack` other than python libraries? Maybe we should provide something like `PyReverseDims` for conversion to row major but don't do it by default? For now, I think a warning should suffice in the documentation. Once we have something working maybe we can even open an issue with the `dlpack` spec itself because it doesn't provide any info about memory layout?

**Comment by pabloferz** [comment]
I had almost forgotten about this (it's been a year and a half). The strides information already determines the memory layout. I remember now that when I thought of this not all python libraries were correctly taking the stride information into account. And that is still the case at least for jax, for instance (but I believe torch should work fine).

**Comment by rejuvyesh** [comment]
```julia
function via_dlpack(x)
    dla = DLArray(@pycall dlpack.to_dlpack(x)::PyObject)
    if DLPack.device_type(dla) == DLPack.kDLCPU
        arr = Base.unsafe_wrap(Array, dla)
    elseif DLPack.device_type(dla) == DLPack.kDLCUDA
        arr = Base.unsafe_wrap(CuArray, dla)
    end
    sz = size(dla)
    st = strides(dla)
    T = eltype(dla)
    if !f_contiguous(T, sz, st)
        arr = rowmajor2colmajor(arr)
    end
    return arr
end
```

would be the correct way to import arrays via `dlpack` to julia.

**Comment by rejuvyesh** [comment]
I am guessing we still need something like:
```julia
function DLTensor(jlarr::StridedArray{T,N}) where {T,N}
    data = pointer(jlarr)
    ctx = DLDevice(kDLCPU, Cint(0))
    ndim = Cint(N)
    dtype = jltypes_to_dtypes()[T]
    shape = pointer(collect(size(jlarr)))
    strides = C_NULL
    byte_offset = Culonglong(0)
    return DLTensor(data, ctx, ndim, dtype, shape, strides, byte_offset)
end
```
and pass to `@pycheck ccall(:PyCapsure_New ,. ..)` to construct a `PyObject` that can be used by torch/jax `from_dlpack`?

**Comment by pabloferz** [comment]
Yes, something like this. I have a PR in the works, but is a bit more involved that just that because again, we need to keep the original array around while the tensor generated on the python side is around.
