### ISSUE TITLE
Is `GC.@preserve` enough?

### ISSUE THREAD

**Issue by rejuvyesh** [pabloferz/DLPack.jl#14]
I am seeing a bunch of memory corruption in https://github.com/rejuvyesh/PyCallChainRules.jl/pull/10 which go away if I wrap the tests inside `GC.enable(false)` and `GC.enable(true)`. Still trying to figure out a MWE because this is not as consistent with simple use of `dlpack`.

**Comment by pabloferz** [comment]
Can you check if after #15 you still see this issue?

**Comment by rejuvyesh** [comment]
It's possible that I am doing it wrong (I don't have any `GC.@preserve` in my codebase), but I still get the same issues. Everything passes with `GC.enable(false)` but memory corruption otherwise. I updated the code to work with the new DLPack at https://github.com/rejuvyesh/PyCallChainRules.jl/pull/10.

**Comment by pabloferz** [comment]
Fixed in #16
