### ISSUE TITLE
is this package actively maintained?

### ISSUE THREAD

**Issue by CarloLucibello** [pabloferz/DLPack.jl#44]
Hi @pabloferz,
since I started relying on this package for some of my projects I wanted to make sure it will keep working in the long term. I see in #43 some CI issues and a lack of response to a simple (and useful) PR that gets me worried. 
Maybe moving this package to an org would help maintenance? Possibilities would be JuliaGenAI, FluxML, JuliaML, ...

**Comment by pabloferz** [comment]
@CarloLucibello. I plan to keep maintaining the package. Regarding the open PR, I contacted the author privately over email and I'm planning on a review soon.

Between the holidays and getting a newborn I haven't been as quick as I or others like may want/expect. That being said. I also don't have an issue with the package being hosted at some organization.

**Comment by CarloLucibello** [comment]
this is very good to know!

> getting a newborn 

congratulations! same here :)

**Comment by pabloferz** [comment]
> congratulations! same here :)
Nice! Congratulations as well!
